//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public int ID { get; set; }
        public int Quantity { get; set; }
        public string StatusOrder { get; set; }
        public float TotalPrice { get; set; }
        public float SubTotalPrice { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
